sdfsdf

diff --git a/android/android-emulator-msic-cmds b/android/android-emulator-msic-cmds
--- a/android/android-emulator-msic-cmds
+++ b/android/android-emulator-msic-cmds
@@ -93,22 +93,57 @@ adb install -r app/build/outputs/apk/app-debug-unaligned.apk -s 02157df2c2460c0b
 #run the app
 adb shell am start -n com.example.android.sunshine.app/com.example.android.sunshine.app.MainActivityfsdfsdf
 
-#load app
+\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
+\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
+\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
+\\\\\\\\\\\\\\\\\\\\\\\\\\\\run instrumentation tests from cmd line
+\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
+\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
+\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
+#remove apk and test 
+emulator -avd $(emulator -list-avds | grep 23) -port 5558  &
+adb -s 1215fcd938411e04 shell "pm uninstall com.overstock.android.prototype"
+adb -s 1215fcd938411e04 shell "pm uninstall com.overstock.android.prototype.test"
+gradle clean assembleDebug (build apk and test apk)
+#load app to device with id 1215fcd938411e04 (found using cmd adb devices) 
 adb push /home/itowey/dev/git_repos/oapp-prototype/app/build/outputs/apk/OApp-debug.apk /data/local/tmp/com.overstock.android.prototype
 adb shell pm install -r "/data/local/tmp/com.overstock.android.prototype"
-
 #load test app
 adb push /home/itowey/dev/git_repos/oapp-prototype/app/build/outputs/apk/OApp-debug-androidTest-unaligned.apk /data/local/tmp/com.overstock.android.prototype.test
 adb shell pm install -r "/data/local/tmp/com.overstock.android.prototype.test"
-
 #Running a specific test
-adb shell am instrument -w -r   -e debug false -e class com.overstock.android.prototype.espresso.activity.CommunitiesActivityTest com.overstock.android.prototype.test android.support.test.runner.AndroidJUnitRunner
+adb shell am instrument -w -r   -e debug false -e class com.overstock.android.prototype.espresso.activity.FeedActivityTest com.overstock.android.prototype.test/android.support.test.runner.AndroidJUnitRunner
+
+gradle app:connectedAndroidTest -Pandroid.testInstrumentationRunnerArguments.class=com.overstock.android.prototype.espresso.activity.BrandActivityTest
 
 #Running tests in a package
 adb shell am instrument -w -r   -e package com.overstock.android.prototype.espresso.activity -e debug false com.overstock.android.prototype.test/android.support.test.runner.AndroidJUnitRunner
 
 #
 sdk use gradle 2.13 && gradle clean assembleDebugAndroidTest uninstallDebug connectedDebugAndroidTest --stacktrace
+
+export releaseVersion=$(echo $(cat $WORKSPACE/app/gradle.properties) | grep -o [0-9]\.[0-9])
+if [ ! -z $releaseVersion ]
+then
+export BUILD_VERSION=$releaseVersion
+export newVersion=$(echo "$releaseVersion +0.1" | bc)-SNAPSHOT
+./gradlew clean assembleRelease && ./gradlew release -Prelease.releaseVersion=$releaseVersion -Prelease.newVersion=$newVersion
+echo "$releaseVersion created"
+else
+echo "Failure : Version NOT created"
+exit 1
+fi
+
+export BUILD_NUMBER=21
+export STORE_PASSWORD=0app0ver5tok
+export KEY_PASSWORD=al1a5pwd!
+git checkout master
+git checkout .
+git pull 
+gradle clean assembleRelease && gradle release -Prelease.releaseVersion=$releaseVersion -Prelease.newVersion=$newVersion -DsigningConfig.storePassword=$STORE_PASSWORD -DsigningConfig.keyPassword=$KEY_PASSWORD --stacktrace
+gradle clean assembleRelease && gradle release -Prelease.releaseVersion=$releaseVersion -Prelease.newVersion=$newVersion -DsigningConfig.storePassword=$STORE_PASSWORD -DsigningConfig.keyPassword=$KEY_PASSWORD -DBUILD_NUMBER=$releaseBuildNumber -DBUILD_VERSION=$releaseVersion --stacktrace
+./gradlew assemble release -Prelease.releaseVersion=$releaseVersion -Prelease.newVersion=$newVersion
+
 
 
 sdk use gradle 2.13
@@ -127,7 +162,8 @@ alias gradle_it='sdk use gradle 2.13 && gradle clean assembleDebug assembleDebug
 
 sdk use gradle 2.13 && gradle clean assembleDebug
 emulator -avd $(emulator -list-avds | grep 23) -port 5558  &
-adb -s emulator-5558 shell "pm uninstall com.overstock.android.prototype"
+adb -s emulator-5554 shell "pm uninstall com.overstock.android.prototype"
+
 adb install -r app/build/outputs/apk/app-debug-unaligned.apk -s emulator-5558
 
 
